name: Laxman Dhulipala
email: ldhulipa@cs.cmu.edu
url: http://ldhulipala.github.io
baseurl: /~laxman
#baseurl: ""

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  fenced_code_blocks: true

plugins:
  - jekyll-redirect-from
