name: Kishen N Gowda
email: kishen19@cs.umd.edu
url: http://kishen19.github.io
baseurl: ""

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  fenced_code_blocks: true

plugins:
  - jekyll-redirect-from
