name: Kishen N Gowda
email: kishen19@cs.umd.edu
url: https://cats.cs.umd.edu/
baseurl: ""

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  fenced_code_blocks: true

plugins:
  - jekyll-redirect-from
